### ISSUE TITLE
Fail msbuild on security issues

### ISSUE THREAD

**Issue by ponsakthi** [Microsoft/DevSkim-VisualStudio-Extension#3]
Though security issues are shown as errors while using the plugin, the actual build succeeds.

Is there any way to fail the build in case of such security issues?

**Comment by PavelBansky** [comment]
Failing build is currently, not supported. It is not even on the roadmap, but I'll put it onto ideas list.
I'm going to close the issue, but feel free to reopen it. I would interested to hear about specific scenario where failing build would be desirable.

**Comment by jnm2** [comment]
Packaging the analyzer on NuGet would enable failing the build. See https://github.com/Microsoft/DevSkim-VisualStudio-Extension/issues/2.

**Comment by PavelBansky** [comment]
I guess I don't understand your statement. How would analyzer on NuGet failed the build?

**Comment by jnm2** [comment]
Unlike a VSIX-deployed analyzer, if you reference an analyzer deployed as a development-time dependency NuGet package via `<PackageReference>` or `project.json` or `packages.config`, you can integrate it into the build process so that suggestions, warnings and errors show up as you build. It's super useful for continuous integration.

**Comment by PavelBansky** [comment]
DevSkim is not a Roslyn analyzer, so this would not work. You can use the command line interface, that we have as a code sample...

**Comment by jnm2** [comment]
I see, but I suppose there's also no reason it couldn't be wrapped up as a Roslyn analyzer. You get access to the text for regexes and can report errors.

CLI works too though!

**Comment by jnm2** [comment]
CLI works too though!

**Comment by PavelBansky** [comment]
We can't make it Roslyn analyzer, because Roslyn is limited to managed code only. The C/CPP/Python build process would not even trigger it..

**Comment by jnm2** [comment]
Of course not, but .NET projects and tools would be able to integrate it into their build pipeline. Sounds more like a community project though.

**Comment by joshbw** [comment]
@jnm2 I'm chatting with the folks that make PumaScan about that specific scenario.  They make an open source (and a more capable commercial) security analyzer for Roslyn.  We are going to give them a PR for our existing security relevant Roslyn analyzers (since ours are spread across a bunch of different analyzer packages - the xml analyzer for xml security flaws, the crypto analyzer for crypto flaws, etc. -  and so are not easy to deploy in the current scheme), and hopefully also figure out how to bundle DevSkim in the same nuget.  The idea would be that Roslyn handle the .Net analysis, since it has an overall more capable engine (builds AST, so understands types, namespaces, etc.), and DevSkim would handle everything that wasn't .Net (including .Net related things, like web.config files, that Roslyn technically can analyze, but is super painful to do so)


Their repo is at https://github.com/pumasecurity/ if you are interested in checking it out.  @ejohn20 has been super open to collaboration, and I'm sure would be open to feedback, suggestions, or PRs

**Comment by ejohn20** [comment]
Absolutely, we're open to this. We currently have the issues hard coded to warning to avoid blocking releases, etc. But, I've had a few requests to allow configuring the severity for given rules (error, warning, etc.). I'm open to making this configurable down the road.
