### ISSUE TITLE
How to list all security issues

### ISSUE THREAD

**Issue by jnm2** [Microsoft/DevSkim-VisualStudio-Extension#7]
I'm not seeing any security issues in a large project I'm looking at with the VS extension installed.
What's the best way to get a list so that I know for sure whether the solution has any DevSkim issues?

**Comment by joshbw** [comment]
Hmm, @Scovetta and @PavelBansky - what do you think the right mechanism would be to bubble up this info.  It seems like we at the very least should auto-filter by the technologies we see, so that we aren't inundating a person with non-relevant checks (e.g. listing out Java checks for c#).  On the VSC side of things I'm a little further limited by what UI widgets I have to display info in, but that's my own problem to solve.  

@jnm2 - can you tell me what languages/app types (web app, console app, etc.) you are analyzing, so short term I can just give you a list of what things DevSkim will be looking for?  At the moment our list is relatively small per technology, as we focus on building out the sophistication of our rules engine over authoring rules (hence why we are in preview), but if there are specific classes of vulnerability you would like us to prioritize rules for just let us know

**Comment by jnm2** [comment]
@joshbw The large projects I want to run it against are all C#: NUnit framework and runners, the Cake project, and line-of-business apps in Windows Forms and WPF. Depending how applicable it is, I was also curious to run it against smaller web projects and personal utilities.
Thanks! This was more to learn what DevSkim can provide than to meet a known need, so I have no specific class of vulnerability in mind.

**Comment by PavelBansky** [comment]
The problem is that DevSkim is editor extension. Until file is not open in editor, devskim doesn't know about it...

**Comment by jnm2** [comment]
This could also be solved with https://github.com/Microsoft/DevSkim-VisualStudio-Extension/issues/3#issuecomment-326148927.

**Comment by scovetta** [comment]
You could also use the new, and very basic [command line interface](https://github.com/Microsoft/DevSkim/tree/master/src/Microsoft.DevSkim/Microsoft.DevSkim.CLI) to scan a directory. You'll need to build the CLI yourself at the moment, but it will output either JSON or text.

To just check to make sure that the DevSkim extension is working, you can just create a new file and add the text `MD5` to it.

**Comment by jnm2** [comment]
It this was tracking work that you still want to do, please feel free to reopen! Otherwise, cleaning up due to inactivity.
